config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "test_view_loader/index"
  root "test_view_loader#index"
  get "test_react_loader/index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include Realm::Support::Pickable

  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # helper ApplicationHelper

  include ReactComponentHelper
end

app/controllers/test_react_loader_controller.rb
class TestReactLoaderController < ApplicationController
  layout "blank"
  def index
    @dashboard = {}

    render_react_component "dashboard/components/App", show_search: true, **@dashboard
  end
end

app/controllers/test_view_loader_controller.rb
class TestViewLoaderController < ApplicationController
  layout "blank"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def top_bar_back_button(path: :back)
    content_for(:top_bar) do
      render TopBar::BarComponent.new(auth_descriptor: current_auth_descriptor, search: false, back_button: path)
    end
  end

  # rubocop:todo Rails/HelperInstanceVariable
  def title
    if content_for?(:page_title)
      content_for(:page_title)
    elsif @page_title.present?
      @page_title
    else
      t("#{controller_path.tr('/', '.')}.#{action_name}.page_title", default: t("global.app_name"))
    end
  end
  # rubocop:enable Rails/HelperInstanceVariable

  # Given a form returns a name for the given path
  def form_field_name(form, path)
    form.object_name + path
  end

  def slim_class(class_string)
    class_string.split(".").join(" ")
  end

  def serialize_react(object)
    case object
    when Hash
      object.transform_keys { |k|
        k.to_s.camelize(:lower)
      }.transform_values do |value|
        serialize_react(value)
      end
    when Enumerable
      object.map { |o| serialize_react(o) }
    when ActiveType::Object, Dry::Struct
      if object.respond_to?(:to_h)
        serialize_react(object.to_h)
      else
        serialize_react(object.attributes)
      end
    when Symbol
      object.to_s
    else
      object
    end
  end

  def boolean_string(b)
    b ? "Yes" : "No"
  end
end

app/helpers/mailer_context_helper.rb
module MailerContextHelper
  # rubocop:todo Rails/HelperInstanceVariable
  def mailer_context(local_assigns = {})
    @ctx || local_assigns[:ctx]
  end
  # rubocop:enable Rails/HelperInstanceVariable
end

app/helpers/react_component_helper.rb
module ReactComponentHelper
  def render_react_component(component_path, **options)
    react_params = options.merge(auth_descriptor: {})
    back_path = react_params.delete(:back_path)
    show_search = react_params.delete(:show_search)

    render(
      "/react_component",
      locals: {
        component_path: component_path,
        react_params:   react_params,
        back_path:      back_path,
        show_search:    show_search,
      }
    )
  end
end

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%#= stylesheet_pack_tag 'application', media: 'all' %>
<%#= javascript_pack_tag 'application' %>
<%#= javascript_pack_tag 'volt' %>
<%= vite_client_tag %>
<%= vite_javascript_tag 'application' %>
<%= vite_javascript_tag 'volt' %>
<%= vite_stylesheet_tag 'application.scss' %>

<script crossorigin="anonymous" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" src="https://code.jquery.com/jquery-3.6.0.min.js">

</script><% if Rails.env.production?
 %><%= render partial: 'layouts/analytics' %>
<% end %>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render partial: "layouts/head" %>
</head><body>
<main>
<%= yield %>
</main></body></html>

app/views/test_view_loader/index.html.erb
<h1>Test View - ERB</h1>
<ul><%= link_to "Test React", test_react_loader_index_path %></ul>